/**
 * Wikipedia / display-name aliases for player name resolution.
 * Keys and values use normalizePlayerNameKey() form (lowercase, no accents).
 */
export const PLAYER_NAME_ALIASES: Record<string, string> = {
  "robbie hunter paul": "robbie hunterpaul",
  "robbie hunterpaul": "robbie hunter paul",
  "robbie paul": "robbie hunterpaul",
  "leslie vainikolo": "lesley vainikolo",
  "lesley vainikolo": "leslie vainikolo",
  "denis moran": "dennis moran",
  "dennis moran": "denis moran",
  "jamie jones buchanan": "jamie jones-buchanan",
  "jamie jones-buchanan": "jamie jones buchanan",
  "ian thornley": "iain thornley",
  "iain thornley": "ian thornley",
  "stephen snitch": "steve snitch",
  "stephen steve snitch": "steve snitch",
  "thomas makinson": "tommy makinson",
  "tom makinson": "tommy makinson",
  "iosia soliola": "sia soliola",
  "sia soliola": "iosia soliola",
  "matty dawson": "matty dawson-jones",
  "richard mathers": "richie mathers",
  "richie mathers": "richard mathers",
  "mike mcilorum": "michael mcilorum",
  "michael mcilorum": "mike mcilorum",
  "micky higham": "michael higham",
  "mickey higham": "michael higham",
  "mick higham": "michael higham",
  "danny mcguire": "daniel mcguire",
  "daniel mcguire": "danny mcguire",
  "george flanagan jr": "george flanagan",
  "george flanagan junior": "george flanagan",
  "jonathon goddard": "jonathan goddard",
  "jonathan goddard": "jonathon goddard",
  "bradley oneill": "bradley o neill",
  "bradley o neill": "bradley oneill",
  "bradley o'neill": "bradley oneill",
  "sala faalogo": "sala fa alogo",
  "sala fa alogo": "sala faalogo",
  "marcus st hilaire": "marcus saint hilaire",
  "marcus saint hilaire": "marcus st hilaire",
  "kevin sinfield": "kevin sinfield",
  "remi casty": "remi casty",
  "elo pelissier": "eloi pelissier",
  "eloi pelissier": "elo pelissier",
  "gregory mounis": "gregory mounis",
  "sebastien raguin": "sebastien raguin",
  "theo fages": "theo fages",
  "gareth o brien": "gareth o'brien",
  "gareth obrien": "gareth o'brien",
  "sean oloughlin": "sean o'loughlin",
  "junior sau": "junior sa'u",
  "junior sa u": "junior sa'u",
  "keanan brand": "keanan brand",
  "jayden okunbor": "jayden okunbor",
};
