/**
 * Add Wikipedia-sourced players missing from near-complete (12/13) Era squads.
 * Sources: en.wikipedia.org season squad tables cited in era-wikipedia-audit-report.
 *
 * Run: npx tsx scripts/add-era-near-miss-players.ts && npm run merge:players
 */
import { readFileSync, writeFileSync } from "fs";
import { join } from "path";

type RawPlayer = Record<string, unknown> & { id: string };

const ADDITIONS_PATH = join(process.cwd(), "data", "player-additions.json");

/** Players verified from Wikipedia season pages — do not invent stats. */
const NEAR_MISS_PLAYERS: RawPlayer[] = [
  {
    id: "bradford-hist-marc-herbert",
    name: "Marc Herbert",
    position: "SCRUM_HALF",
    club: "Bradford Bulls",
    nationality: "Australia",
    era: "MODERN_ERA",
    yearsActive: "2010–2011",
    category: "historic",
    peakRating: 80,
    rating: 80,
    value: 450000,
    appearances: 21,
    tries: 4,
    sourceUrl: "https://en.wikipedia.org/wiki/2011_Bradford_Bulls_season",
  },
  {
    id: "bradford-hist-cain-southernwood",
    name: "Cain Southernwood",
    position: "SCRUM_HALF",
    club: "Bradford Bulls",
    nationality: "England",
    era: "MODERN_ERA",
    yearsActive: "2011–2011",
    category: "historic",
    peakRating: 76,
    rating: 76,
    value: 135000,
    appearances: 0,
    tries: 0,
    sourceUrl: "https://en.wikipedia.org/wiki/2011_Bradford_Bulls_season",
  },
  {
    id: "leeds-hist-beau-falloon",
    name: "Beau Falloon",
    position: "HOOKER",
    club: "Leeds Rhinos",
    nationality: "Australia",
    era: "MODERN_ERA",
    yearsActive: "2016–2016",
    category: "historic",
    peakRating: 78,
    rating: 78,
    value: 350000,
    appearances: 11,
    tries: 0,
    birthYear: 1987,
    dateOfBirth: "1987-05-21",
    sourceUrl: "https://en.wikipedia.org/wiki/2016_Leeds_Rhinos_season",
  },
  {
    id: "catalans-hist-shane-perry",
    name: "Shane Perry",
    position: "SCRUM_HALF",
    club: "Catalans Dragons",
    nationality: "Australia",
    era: "MODERN_ERA",
    yearsActive: "2008–2009",
    category: "historic",
    peakRating: 79,
    rating: 79,
    value: 400000,
    appearances: 16,
    tries: 1,
    sourceUrl: "https://en.wikipedia.org/wiki/2009_Catalans_Dragons_season",
  },
  {
    id: "bradford-hist-max-clarke",
    name: "Max Clarke",
    position: "CENTRE",
    club: "Bradford Bulls",
    nationality: "England",
    era: "MODERN_ERA",
    yearsActive: "2023–2023",
    category: "historic",
    peakRating: 77,
    rating: 77,
    value: 200000,
    appearances: 0,
    tries: 0,
    sourceUrl: "https://en.wikipedia.org/wiki/2023_Bradford_Bulls_season",
  },
  {
    id: "bradford-hist-mikey-wood",
    name: "Mikey Wood",
    position: "LOOSE_FORWARD",
    club: "Bradford Bulls",
    nationality: "England",
    era: "MODERN_ERA",
    yearsActive: "2019–2021",
    category: "historic",
    peakRating: 79,
    rating: 79,
    value: 350000,
    appearances: 24,
    tries: 1,
    sourceUrl: "https://en.wikipedia.org/wiki/2019_Bradford_Bulls_season",
  },
  {
    id: "bradford-hist-george-milton",
    name: "George Milton",
    position: "LOOSE_FORWARD",
    club: "Bradford Bulls",
    nationality: "England",
    era: "MODERN_ERA",
    yearsActive: "2019–2019",
    category: "historic",
    peakRating: 76,
    rating: 76,
    value: 135000,
    appearances: 0,
    tries: 0,
    sourceUrl: "https://en.wikipedia.org/wiki/2019_Bradford_Bulls_season",
  },
  {
    id: "salford-hist-john-wilshire",
    name: "John Wilshire",
    position: "WING",
    club: "Salford Red Devils",
    nationality: "England",
    era: "MODERN_ERA",
    yearsActive: "2009–2009",
    category: "historic",
    peakRating: 78,
    rating: 78,
    value: 300000,
    appearances: 0,
    tries: 0,
    sourceUrl: "https://en.wikipedia.org/wiki/2009_Salford_City_Reds_season",
  },
  {
    id: "salford-hist-andrew-thornley",
    name: "Andrew Thornley",
    position: "WING",
    club: "Salford Red Devils",
    nationality: "England",
    era: "MODERN_ERA",
    yearsActive: "2009–2009",
    category: "historic",
    peakRating: 77,
    rating: 77,
    value: 200000,
    appearances: 0,
    tries: 0,
    sourceUrl: "https://en.wikipedia.org/wiki/2009_Salford_City_Reds_season",
  },
  {
    id: "bradford-hist-billy-jowitt",
    name: "Billy Jowitt",
    position: "STAND_OFF",
    club: "Bradford Bulls",
    nationality: "England",
    era: "MODERN_ERA",
    yearsActive: "2020–2022",
    category: "historic",
    peakRating: 77,
    rating: 77,
    value: 200000,
    appearances: 3,
    tries: 0,
    sourceUrl: "https://en.wikipedia.org/wiki/2022_Bradford_Bulls_season",
  },
  {
    id: "bradford-hist-ross-oakes",
    name: "Ross Oakes",
    position: "CENTRE",
    club: "Bradford Bulls",
    nationality: "England",
    era: "MODERN_ERA",
    yearsActive: "2017–2022",
    category: "historic",
    peakRating: 80,
    rating: 80,
    value: 350000,
    appearances: 22,
    tries: 3,
    sourceUrl: "https://en.wikipedia.org/wiki/2021_Bradford_Bulls_season",
  },
  {
    id: "bradford-hist-joe-burton",
    name: "Joe Burton",
    position: "CENTRE",
    club: "Bradford Bulls",
    nationality: "England",
    era: "MODERN_ERA",
    yearsActive: "2021–2022",
    category: "historic",
    peakRating: 76,
    rating: 76,
    value: 135000,
    appearances: 7,
    tries: 1,
    sourceUrl: "https://en.wikipedia.org/wiki/2021_Bradford_Bulls_season",
  },
  {
    id: "bradford-hist-eldon-myers",
    name: "Eldon Myers",
    position: "CENTRE",
    club: "Bradford Bulls",
    nationality: "England",
    era: "MODERN_ERA",
    yearsActive: "2021–2021",
    category: "historic",
    peakRating: 75,
    rating: 75,
    value: 135000,
    appearances: 2,
    tries: 0,
    sourceUrl: "https://en.wikipedia.org/wiki/2021_Bradford_Bulls_season",
  },
  {
    id: "bradford-hist-sam-smith",
    name: "Sam Smith",
    position: "CENTRE",
    club: "Bradford Bulls",
    nationality: "England",
    era: "MODERN_ERA",
    yearsActive: "2021–2021",
    category: "historic",
    peakRating: 74,
    rating: 74,
    value: 135000,
    appearances: 0,
    tries: 0,
    sourceUrl: "https://en.wikipedia.org/wiki/2021_Bradford_Bulls_season",
  },
  {
    id: "bradford-hist-brad-england",
    name: "Brad England",
    position: "SECOND_ROW",
    club: "Bradford Bulls",
    nationality: "England",
    era: "MODERN_ERA",
    yearsActive: "2021–2022",
    category: "historic",
    peakRating: 79,
    rating: 79,
    value: 350000,
    appearances: 18,
    tries: 4,
    sourceUrl: "https://en.wikipedia.org/wiki/2021_Bradford_Bulls_season",
  },
  {
    id: "bradford-hist-adam-rooks",
    name: "Adam Rooks",
    position: "SECOND_ROW",
    club: "Bradford Bulls",
    nationality: "England",
    era: "MODERN_ERA",
    yearsActive: "2021–2021",
    category: "historic",
    peakRating: 78,
    rating: 78,
    value: 300000,
    appearances: 14,
    tries: 2,
    sourceUrl: "https://en.wikipedia.org/wiki/2021_Bradford_Bulls_season",
  },
  {
    id: "bradford-hist-brad-gallagher",
    name: "Brad Gallagher",
    position: "SECOND_ROW",
    club: "Bradford Bulls",
    nationality: "England",
    era: "MODERN_ERA",
    yearsActive: "2020–2021",
    category: "historic",
    peakRating: 77,
    rating: 77,
    value: 200000,
    appearances: 7,
    tries: 0,
    sourceUrl: "https://en.wikipedia.org/wiki/2021_Bradford_Bulls_season",
  },
  {
    id: "bradford-hist-callum-bustin",
    name: "Callum Bustin",
    position: "CENTRE",
    club: "Bradford Bulls",
    nationality: "England",
    era: "MODERN_ERA",
    yearsActive: "2018–2018",
    category: "historic",
    peakRating: 78,
    rating: 78,
    value: 250000,
    appearances: 20,
    tries: 7,
    sourceUrl: "https://en.wikipedia.org/wiki/2018_Bradford_Bulls_season",
  },
  {
    id: "bradford-hist-tuoyo-egodo",
    name: "Tuoyo Egodo",
    position: "WING",
    club: "Bradford Bulls",
    nationality: "England",
    era: "MODERN_ERA",
    yearsActive: "2018–2018",
    category: "historic",
    peakRating: 79,
    rating: 79,
    value: 350000,
    appearances: 8,
    tries: 5,
    sourceUrl: "https://en.wikipedia.org/wiki/2018_Bradford_Bulls_season",
  },
  {
    id: "bradford-hist-jake-butler-fleming",
    name: "Jake Butler-Fleming",
    position: "CENTRE",
    club: "Bradford Bulls",
    nationality: "Australia",
    era: "MODERN_ERA",
    yearsActive: "2018–2018",
    category: "historic",
    peakRating: 77,
    rating: 77,
    value: 200000,
    appearances: 2,
    tries: 1,
    sourceUrl: "https://en.wikipedia.org/wiki/2018_Bradford_Bulls_season",
  },
  {
    id: "castleford-hist-james-grehan",
    name: "James Grehan",
    position: "CENTRE",
    club: "Castleford Tigers",
    nationality: "England",
    era: "MODERN_ERA",
    yearsActive: "2012–2012",
    category: "historic",
    peakRating: 76,
    rating: 76,
    value: 135000,
    appearances: 4,
    tries: 0,
    sourceUrl: "https://en.wikipedia.org/wiki/2012_Castleford_Tigers_season",
  },
  {
    id: "catalans-hist-renaud-guigue",
    name: "Renaud Guigue",
    position: "FULLBACK",
    club: "Catalans Dragons",
    nationality: "France",
    era: "MODERN_ERA",
    yearsActive: "2006–2006",
    category: "historic",
    peakRating: 78,
    rating: 78,
    value: 300000,
    appearances: 21,
    tries: 3,
    sourceUrl: "https://en.wikipedia.org/wiki/2006_Catalans_Dragons_season",
  },
  {
    id: "catalans-hist-mark-hughes",
    name: "Mark Hughes",
    position: "CENTRE",
    club: "Catalans Dragons",
    nationality: "Australia",
    era: "MODERN_ERA",
    yearsActive: "2006–2006",
    category: "historic",
    peakRating: 80,
    rating: 80,
    value: 400000,
    appearances: 26,
    tries: 11,
    sourceUrl: "https://en.wikipedia.org/wiki/2006_Catalans_Dragons_season",
  },
  {
    id: "catalans-hist-teddy-sadaoui",
    name: "Teddy Sadaoui",
    position: "CENTRE",
    club: "Catalans Dragons",
    nationality: "France",
    era: "MODERN_ERA",
    yearsActive: "2006–2006",
    category: "historic",
    peakRating: 76,
    rating: 76,
    value: 135000,
    appearances: 7,
    tries: 0,
    sourceUrl: "https://en.wikipedia.org/wiki/2006_Catalans_Dragons_season",
  },
  {
    id: "salford-hist-reni-maitua",
    name: "Reni Maitua",
    position: "SECOND_ROW",
    club: "Salford Red Devils",
    nationality: "Australia",
    era: "MODERN_ERA",
    yearsActive: "2015–2015",
    category: "historic",
    peakRating: 82,
    rating: 82,
    value: 550000,
    appearances: 6,
    tries: 0,
    sourceUrl: "https://en.wikipedia.org/wiki/2015_Salford_Red_Devils_season",
  },
];

function main(): void {
  const additions = JSON.parse(readFileSync(ADDITIONS_PATH, "utf-8")) as {
    current: RawPlayer[];
    historic: RawPlayer[];
    legend?: RawPlayer[];
  };

  if (!additions.historic) additions.historic = [];
  const existingIds = new Set(additions.historic.map((p) => p.id));

  let added = 0;
  for (const player of NEAR_MISS_PLAYERS) {
    if (existingIds.has(player.id)) {
      console.log(`  skip (already queued): ${player.id}`);
      continue;
    }
    additions.historic.push(player);
    existingIds.add(player.id);
    added++;
    console.log(`  queued: ${player.name} (${player.id})`);
  }

  writeFileSync(ADDITIONS_PATH, `${JSON.stringify(additions, null, 2)}\n`);
  console.log(`\nAdded ${added} players to player-additions.json`);
}

main();
