/**
 * Split data/current-squads.json into per-club chunks for code-split loading.
 * Run: npm run build:player-chunks
 */
import { mkdirSync, readFileSync, writeFileSync } from "fs";
import { join } from "path";

const ROOT = join(process.cwd(), "data");
const OUT = join(ROOT, "players", "chunks", "current");
const LOADERS = join(
  process.cwd(),
  "src/lib/players/generated/current-chunk-imports.ts"
);

function slugifyClub(club: string): string {
  return club
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "");
}

function main() {
  const squads = JSON.parse(
    readFileSync(join(ROOT, "current-squads.json"), "utf8")
  ) as Record<string, unknown>[];

  const byClub = new Map<string, Record<string, unknown>[]>();
  for (const row of squads) {
    const club = String(row.club ?? row.team ?? "unknown");
    const list = byClub.get(club) ?? [];
    list.push(row);
    byClub.set(club, list);
  }

  mkdirSync(OUT, { recursive: true });
  mkdirSync(join(process.cwd(), "src/lib/players/generated"), {
    recursive: true,
  });

  const manifest: { club: string; slug: string; file: string; count: number }[] =
    [];
  const loaderLines: string[] = [
    "// Auto-generated by scripts/split-current-squads-chunks.ts — do not edit.",
    "",
    'type RawPlayer = Record<string, unknown>;',
    "",
    "export async function loadAllCurrentClubChunks(): Promise<RawPlayer[]> {",
    "  const chunks = await Promise.all([",
  ];

  for (const [club, players] of byClub.entries()) {
    const slug = slugifyClub(club);
    const file = `${slug}.json`;
    writeFileSync(join(OUT, file), JSON.stringify(players, null, 2));
    manifest.push({ club, slug, file, count: players.length });
    loaderLines.push(
      `    import("../../../../data/players/chunks/current/${file}").then((m) => m.default as RawPlayer[]),`
    );
  }

  loaderLines.push(
    "  ]);",
    "  return chunks.flat();",
    "}",
    ""
  );

  manifest.sort((a, b) => a.club.localeCompare(b.club));
  writeFileSync(
    join(OUT, "manifest.json"),
    JSON.stringify({ clubs: manifest }, null, 2)
  );
  writeFileSync(LOADERS, loaderLines.join("\n"));

  console.log(
    `Wrote ${manifest.length} club chunks and ${LOADERS}`
  );
}

main();
