export type ChampNationalityCode = "ENG" | "FRA" | "NZL" | "AUS" | "SAM" | "FJI" | "TON" | "PNG";

export const CHAMP_NAME_POOLS: Record<
  ChampNationalityCode,
  { first: string[]; last: string[] }
> = {
  ENG: {
    first: [
      "Aaron", "Adam", "Aidan", "Aiden", "Alan", "Albert", "Alex", "Alexander", "Alfie", "Andrew",
      "Anthony", "Archie", "Arthur", "Ashley", "Bailey", "Barry", "Ben", "Benjamin", "Billy", "Blake",
      "Bobby", "Brad", "Bradley", "Brandon", "Brett", "Brian", "Bruce", "Caleb", "Callum", "Cameron",
      "Carl", "Charlie", "Chris", "Christian", "Christopher", "Clive", "Colin", "Connor", "Craig", "Dale",
      "Damian", "Daniel", "Danny", "Darren", "David", "Dean", "Declan", "Dennis", "Derek", "Dominic",
      "Duncan", "Dylan", "Edward", "Elliot", "Ellis", "Ethan", "Evan", "Felix", "Finlay", "Finn",
      "Frankie", "Fred", "Freddie", "Gary", "Gareth", "George", "Gerald", "Glen", "Gordon", "Graham",
      "Grant", "Greg", "Harley", "Harry", "Harvey", "Henry", "Howard", "Hugh", "Hugo", "Ian",
      "Isaac", "Jack", "Jacob", "Jake", "James", "Jamie", "Jason", "Jay", "Jenson", "Jeremy",
      "Joe", "Joel", "John", "Johnny", "Jonathan", "Jordan", "Joseph", "Josh", "Joshua", "Jude",
      "Julian", "Justin", "Karl", "Keith", "Ken", "Kenneth", "Kevin", "Kieran", "Kyle", "Lee",
      "Leo", "Leon", "Lewis", "Liam", "Logan", "Louis", "Lucas", "Luke", "Malcolm", "Marc",
      "Marcus", "Mark", "Martin", "Mason", "Matt", "Matthew", "Max", "Michael", "Miles", "Mitchell",
      "Morgan", "Nathan", "Neil", "Nicholas", "Nick", "Nico", "Noah", "Oliver", "Ollie", "Oscar",
      "Owen", "Patrick", "Paul", "Pete", "Peter", "Philip", "Ralph", "Ray", "Raymond", "Reece",
      "Reggie", "Rhys", "Richard", "Riley", "Robbie", "Robert", "Robin", "Roger", "Ron", "Ross",
      "Roy", "Ryan", "Sam", "Samuel", "Scott", "Sean", "Sebastian", "Shane", "Shaun", "Simon",
      "Sonny", "Stanley", "Stephen", "Steve", "Stuart", "Ted", "Teddy", "Terry", "Theo", "Thomas",
      "Tim", "Timothy", "Toby", "Tom", "Tommy", "Tony", "Travis", "Trevor", "Tristan", "Tyler",
      "Victor", "Vincent", "Wayne", "Will", "William", "Zac", "Zach", "Zachary", "Ashton", "Barney",
    ],
    last: [
      "Abbott", "Adams", "Ainsworth", "Aldridge", "Allen", "Anderson", "Andrews", "Appleby", "Archer", "Armstrong",
      "Arnold", "Ashby", "Ashcroft", "Ashton", "Ashworth", "Aspinall", "Atherton", "Atkinson", "Austin", "Bailey",
      "Baines", "Baker", "Baldwin", "Ball", "Banks", "Barber", "Barker", "Barlow", "Barnes", "Barnett",
      "Barratt", "Barrett", "Barrow", "Barton", "Bateman", "Bates", "Baxter", "Beattie", "Beaumont", "Beckett",
      "Bedford", "Bell", "Bennett", "Benson", "Bent", "Bentley", "Berridge", "Berry", "Birch", "Birtwistle",
      "Bishop", "Black", "Blackburn", "Blackmore", "Blake", "Bleasdale", "Bolton", "Bond", "Booth", "Bowen",
      "Bowers", "Bowman", "Boyd", "Bracewell", "Bracken", "Bradley", "Brady", "Bray", "Breen", "Brennan",
      "Bridges", "Briggs", "Brindle", "Broadbent", "Bromley", "Brookes", "Brooks", "Broughton", "Brown", "Bryant",
      "Buckley", "Bullock", "Burgess", "Burke", "Burns", "Burrows", "Burton", "Butler", "Butterworth", "Byrne",
      "Cain", "Caldwell", "Callaghan", "Cameron", "Campbell", "Carey", "Carlton", "Carpenter", "Carr", "Carroll",
      "Carter", "Cartwright", "Chadwick", "Chambers", "Chapman", "Charles", "Cheetham", "Christie", "Clark", "Clarke",
      "Clayton", "Clements", "Clifford", "Clough", "Coates", "Cobb", "Cockburn", "Coleman", "Collier", "Collinge",
      "Collins", "Connolly", "Connor", "Cook", "Cooper", "Copeland", "Corbett", "Coulson", "Coulthard", "Cowley",
      "Cox", "Craig", "Crawford", "Critchley", "Crompton", "Crosby", "Cross", "Crowther", "Cunliffe", "Cunningham",
      "Curtis", "Dale", "Dalton", "Daniels", "Darlington", "Davenport", "Davidson", "Davies", "Davis", "Dawson",
      "Day", "Dean", "Dewhurst", "Dickinson", "Dixon", "Dobson", "Dodd", "Dolan", "Donaldson", "Donnelly",
      "Donoghue", "Douglas", "Doyle", "Drinkwater", "Duffy", "Dugdale", "Duncan", "Dunn", "Dyson", "Eastwood",
      "Eaton", "Eccles", "Edmondson", "Edwards", "Elliott", "Ellis", "Ellison", "Emerson", "Entwistle", "Evans",
      "Fairclough", "Fairhurst", "Farrar", "Farrell", "Fearnley", "Ferguson", "Field", "Fielding", "Finch", "Firth",
      "Fisher", "Fitzgerald", "Fitzpatrick", "Flanagan", "Fleming", "Fletcher", "Flynn", "Ford", "Forshaw", "Foster",
      "Fothergill", "Fowler", "Fox", "Francis", "Fraser", "Freeman", "Frost", "Gallagher", "Gardiner", "Gardner",
      "Garner", "George", "Gerrard", "Gibbons", "Gibson", "Gilbert", "Gill", "Gilligan", "Glover", "Goodwin",
      "Gordon", "Gorton", "Gould", "Graham", "Grant", "Gray", "Green", "Greenhalgh", "Greenwood", "Gregory",
      "Gregson", "Griffiths", "Grundy", "Hackett", "Hale", "Hall", "Halliwell", "Hamilton", "Hammond", "Hancock",
      "Hanley", "Hansen", "Harding", "Hardy", "Hargreaves", "Harper", "Harris", "Harrison", "Hart", "Harvey",
      "Haslam", "Hatton", "Hawkins", "Hayes", "Haynes", "Hayward", "Heath", "Heaton", "Henderson", "Henry",
      "Heslop", "Hewitt", "Higgins", "Hill", "Hilton", "Hindle", "Hirst", "Hobson", "Hodgson", "Hodson",
      "Holden", "Holland", "Holmes", "Holt", "Hooper", "Hopkins", "Hopwood", "Hornby", "Horne", "Horrocks",
      "Houghton", "Howard", "Howarth", "Howe", "Howells", "Hudson", "Hughes", "Hulme", "Humphreys", "Hunt",
      "Hunter", "Hutchinson", "Hutton", "Hyland", "Ibbotson", "Ingham", "Ingram", "Isherwood", "Jackson", "Jacobs",
      "James", "Jarvis", "Jenkins", "Jennings", "Jepson", "Johnson", "Johnston", "Jolley", "Jones", "Jordan",
      "Joyce", "Kane", "Kay", "Kayley", "Keighley", "Kelly", "Kemp", "Kennedy", "Kent", "Kenyon",
      "Kerr", "Kershaw", "Kilner", "King", "Kirby", "Kirk", "Knight", "Knowles", "Lamb", "Lambert",
      "Lane", "Langley", "Latham", "Lawrence", "Lawson", "Lawton", "Leach", "Leatherbarrow", "Lee", "Leigh",
      "Leonard", "Lewis", "Leyland", "Lightfoot", "Lindsay", "Lister", "Little", "Livesey", "Lloyd", "Lomas",
      "Long", "Lord", "Lowe", "Lucas", "Lunt", "Lynch", "Lyons", "MacDonald", "Mackay", "Madden",
      "Maguire", "Maher", "Makin", "Mallinson", "Mann", "Marsden", "Marsh", "Marshall", "Martin", "Mason",
      "Mather", "Matthews", "May", "McCarthy", "McDonald", "McGee", "McGrath", "McIntosh", "McKenzie", "McLean",
      "McMahon", "Meadows", "Melling", "Metcalfe", "Middleton", "Miles", "Miller", "Mills", "Mitchell", "Molyneux",
      "Moore", "Moorhouse", "Moran", "Morgan", "Morley", "Morris", "Morrison", "Morton", "Moss", "Mulligan",
      "Murphy", "Murray", "Myers", "Nash", "Naylor", "Neal", "Nelson", "Newall", "Newman", "Newton",
      "Nicholls", "Nicholson", "Nolan", "Norman", "Norris", "Norton", "Nuttall", "O'Brien", "O'Connor", "O'Donnell",
      "O'Neill", "Oakes", "Ogden", "Oliver", "Ormerod", "Ormond", "Osborne", "Owen", "Owens", "Page",
      "Palmer", "Parker", "Parkinson", "Parr", "Parry", "Parsons", "Partington", "Patel", "Paterson", "Patrick",
      "Patterson", "Payne", "Pearce", "Pearson", "Peel", "Pemberton", "Pendlebury", "Percival", "Perry", "Peters",
      "Phillips", "Pickering", "Pickles", "Pike", "Pitt", "Platt", "Pollard", "Porter", "Potter", "Powell",
      "Power", "Pratt", "Prescott", "Price", "Priestley", "Pritchard", "Pye", "Quirk", "Quinn", "Radcliffe",
      "Radford", "Rainford", "Ramsay", "Randall", "Rawlinson", "Rayner", "Read", "Redmond", "Reed", "Reeves",
      "Reid", "Reynolds", "Rhodes", "Richards", "Richardson", "Riley", "Rimmer", "Roberts", "Robertson", "Robinson",
      "Robson", "Rogers", "Rooney", "Rose", "Ross", "Rothwell", "Rowe", "Rowley", "Royle", "Russell",
      "Ryan", "Sanders", "Sanderson", "Saunders", "Savage", "Schofield", "Scott", "Seddon", "Sephton", "Shackleton",
      "Sharpe", "Shaw", "Shepherd", "Sherman", "Short", "Shuttleworth", "Siddall", "Simpson", "Sinclair", "Skelton",
      "Slater", "Smalley", "Smith", "Smyth", "Southern", "Speakman", "Spencer", "Standish", "Stanley", "Steele",
      "Stephens", "Stevens", "Stevenson", "Stewart", "Stokes", "Stone", "Stott", "Stringer", "Sullivan", "Summers",
      "Sutcliffe", "Sutton", "Swann", "Swift", "Sykes", "Tattersall", "Taylor", "Thomas", "Thompson", "Thomson",
      "Thornley", "Thornton", "Thorpe", "Tickle", "Tipping", "Todd", "Tomlinson", "Topping", "Townsend", "Tucker",
      "Turner", "Underwood", "Unsworth", "Vaughan", "Waddington", "Wade", "Wainwright", "Walker", "Wall", "Wallace",
      "Walsh", "Walton", "Warburton", "Ward", "Warner", "Warren", "Waters", "Watkins", "Watkinson", "Watson",
      "Watts", "Webb", "Webster", "Welch", "Wells", "West", "Weston", "Whalley", "Wheatley", "Wheeler",
      "White", "Whitehead", "Whiteside", "Whitfield", "Whittaker", "Wignall", "Wild", "Wilkins", "Wilkinson", "Williams",
      "Williamson", "Willis", "Wilson", "Winter", "Withers", "Wood", "Woodcock", "Woods", "Woodward", "Woolfenden",
      "Woolley", "Worsley", "Worthington", "Wright", "Wyatt", "Yarwood", "Yates", "Young",
    ],
  },
  FRA: {
    first: [
      "Adrien", "Alexandre", "Alexis", "Antoine", "Anthony", "Arthur", "Aurelien", "Axel", "Baptiste", "Bastien",
      "Benjamin", "Brice", "Cedric", "Christophe", "Clement", "Corentin", "Damien", "David", "Dorian", "Dylan",
      "Eloi", "Enzo", "Etienne", "Fabien", "Florian", "Francois", "Gabin", "Gaetan", "Gregoire", "Guillaume",
      "Hugo", "Jean", "Jerome", "Jordan", "Jules", "Julien", "Kevin", "Kilian", "Leo", "Lilian",
      "Loic", "Louis", "Lucas", "Marc", "Mathieu", "Mathis", "Maxime", "Mickael", "Morgan", "Nathan",
      "Nicolas", "Noa", "Olivier", "Paul", "Pierre", "Quentin", "Raphael", "Remi", "Romain", "Sebastien",
      "Simon", "Theo", "Thibault", "Thomas", "Tristan", "Valentin", "Victor", "William", "Xavier", "Yann",
      "Yoann", "Yohan",
    ],
    last: [
      "Andrieu", "Armand", "Aussar", "Bardy", "Barre", "Barthe", "Berge", "Bernard", "Bertrand", "Blanc",
      "Bonnet", "Bouchet", "Bourgarel", "Bousquet", "Cabrera", "Carme", "Cavailhes", "Chanareille", "Coste", "Cousin",
      "Da Costa", "David", "Delmas", "Deschamps", "Dubarry", "Dubois", "Ducasse", "Dupont", "Durand", "Escande",
      "Escudier", "Espinas", "Esteve", "Fabre", "Fabregas", "Fages", "Ferrand", "Ferrasse", "Ferrer", "Fontaine",
      "Fournier", "Galin", "Galy", "Garcia", "Garrigues", "Gigot", "Girard", "Gorse", "Henry", "Hernandez",
      "Hilaire", "Homs", "Innocenti", "Isnard", "Izard", "Izquierdo", "Jorda", "Jourdan", "Julian", "Klein",
      "Lacombe", "Lacoste", "Lafon", "Laguerre", "Lapeyre", "Laurent", "Lefebvre", "Leroy", "Marchand", "Marguerite",
      "Marion", "Martin", "Maurin", "Mazars", "Mercier", "Michel", "Moreau", "Mourgue", "Narbonne", "Navarro",
      "Nouguier", "Nouvel", "Ollagnier", "Ortiz", "Pelissier", "Perez", "Petit", "Peyre", "Peyron", "Pons",
      "Pujol", "Quiles", "Rey", "Richard", "Rigal", "Rives", "Riviere", "Robert", "Romano", "Roussel",
      "Roux", "Sabatier", "Salabio", "Sanchez", "Sanz", "Serra", "Simon", "Sole", "Teixeira", "Thomas",
      "Tison", "Tissier", "Torres", "Urbain", "Valette", "Verdier", "Vidal", "Viguier", "Villeneuve", "Vincent",
    ],
  },
  AUS: {
    first: [
      "Aaron", "Adam", "Aidan", "Alex", "Andrew", "Angus", "Ashley", "Bailey", "Beau", "Ben",
      "Blake", "Brad", "Bradley", "Brendan", "Brett", "Brodie", "Callum", "Cameron", "Casey", "Charlie",
      "Chris", "Clinton", "Cody", "Cooper", "Corey", "Craig", "Damien", "Daniel", "Darcy", "Darren",
      "David", "Dean", "Dylan", "Ethan", "Finn", "Fletcher", "Flynn", "Fraser", "Gabe", "Gary",
      "George", "Glen", "Grant", "Harry", "Harvey", "Heath", "Hugo", "Hunter", "Jack", "Jacob",
      "Jake", "James", "Jamie", "Jarrod", "Jason", "Jayden", "Jed", "Jesse", "Joe", "Joel",
      "John", "Jordan", "Josh", "Joshua", "Julian", "Justin", "Kane", "Karl", "Keith", "Kieran",
      "Kyle", "Lachlan", "Lance", "Leo", "Liam", "Logan", "Luke", "Marcus", "Mark", "Mason",
      "Matt", "Matthew", "Max", "Michael", "Mitchell", "Nate", "Nathan", "Nicholas", "Noah", "Oliver",
      "Oscar", "Patrick", "Paul", "Peter", "Reece", "Rhys", "Riley", "Robbie", "Ryan", "Sam",
      "Samuel", "Scott", "Sean", "Shane", "Shaun", "Simon", "Steve", "Stuart", "Thomas", "Tim",
      "Toby", "Tom", "Tony", "Travis", "Troy", "Tyler", "Will", "William", "Zac", "Zach",
    ],
    last: [
      "Adams", "Anderson", "Andrews", "Armstrong", "Ashcroft", "Bailey", "Baker", "Barlow", "Barrett", "Barton",
      "Beaumont", "Bell", "Bennett", "Bentley", "Berry", "Black", "Blake", "Bolton", "Booth", "Bowman",
      "Boyd", "Bradley", "Brooks", "Brown", "Burgess", "Burns", "Burton", "Butler", "Campbell", "Carey",
      "Carr", "Carroll", "Carter", "Cartwright", "Chambers", "Chapman", "Clark", "Clarke", "Coleman", "Collins",
      "Cook", "Cooper", "Cox", "Craig", "Crawford", "Cross", "Cunningham", "Curtis", "Daniels", "Davidson",
      "Davies", "Davis", "Dawson", "Dixon", "Douglas", "Doyle", "Duncan", "Dunn", "Edwards", "Elliott",
      "Ellis", "Evans", "Farrell", "Ferguson", "Field", "Fisher", "Fletcher", "Ford", "Foster", "Fowler",
      "Fox", "Francis", "Fraser", "Freeman", "Gallagher", "Gardner", "Gibson", "Goodwin", "Gordon", "Graham",
      "Grant", "Gray", "Green", "Griffiths", "Hall", "Hamilton", "Hancock", "Harding", "Harper", "Harris",
      "Harrison", "Hart", "Harvey", "Hawkins", "Hayes", "Henderson", "Henry", "Hewitt", "Hill", "Hodgson",
      "Holland", "Holmes", "Hopkins", "Howard", "Hughes", "Hunt", "Hunter", "Ingall", "Jackson", "James",
      "Jenkins", "Jennings", "Johnson", "Johnston", "Jones", "Jordan", "Kelly", "Kennedy", "Kent", "Kerr",
      "King", "Knight", "Lambert", "Lane", "Lang", "Lawrence", "Lawson", "Lee", "Lewis", "Lloyd",
      "Long", "Lynch", "Lyons", "Marsh", "Marshall", "Martin", "Mason", "Matthews", "McCarthy", "McDonald",
      "McKenzie", "McLean", "Miller", "Mills", "Mitchell", "Moore", "Morgan", "Morris", "Morrison", "Murphy",
      "Murray", "Nelson", "Newman", "Newton", "Nicholls", "Nolan", "O'Brien", "O'Connor", "O'Neill", "Oliver",
      "Osborne", "Owen", "Page", "Palmer", "Parker", "Parsons", "Patterson", "Payne", "Pearce", "Pearson",
      "Perry", "Phillips", "Porter", "Powell", "Price", "Quinn", "Reed", "Reeves", "Reid", "Reynolds",
      "Richards", "Richardson", "Riley", "Roberts", "Robertson", "Robinson", "Rogers", "Ross", "Russell", "Ryan",
      "Sanders", "Saunders", "Scott", "Shaw", "Shepherd", "Simpson", "Slater", "Smith", "Spencer", "Steele",
      "Stevens", "Stewart", "Stokes", "Stone", "Sullivan", "Sutton", "Taylor", "Thomas", "Thompson", "Thornton",
      "Todd", "Turner", "Walker", "Wallace", "Walsh", "Ward", "Warren", "Watkins", "Watson", "Watts",
      "Webb", "Wells", "West", "White", "Wilkinson", "Williams", "Williamson", "Wilson", "Wood", "Woods",
      "Wright", "Young", "Cleary", "Cronk", "Gifkins", "Hynes", "Latimore", "Lockyer", "Merrin", "Peachey",
      "Wighton", "Yeo", "Ashby",
    ],
  },
  NZL: {
    first: [
      "Aiden", "Alex", "Arapeta", "Aron", "Arona", "Bailey", "Beauden", "Ben", "Blake", "Brad",
      "Caleb", "Callum", "Cameron", "Casey", "Cody", "Connor", "Cooper", "Corey", "Daniel", "Dean",
      "Dylan", "Ethan", "Finn", "George", "Harry", "Hemi", "Henry", "Hone", "Hugo", "Hunter",
      "Ihaia", "Isaac", "Isaiah", "Jack", "Jacob", "Jake", "James", "Jamie", "Jarrod", "Jayden",
      "Joe", "Joel", "John", "Jordan", "Josh", "Kahurangi", "Kahu", "Kai", "Kaleb", "Kane",
      "Kieran", "Kohu", "Kyle", "Lachlan", "Leo", "Lewis", "Liam", "Logan", "Luke", "Mana",
      "Manu", "Marcus", "Mason", "Matt", "Matthew", "Max", "Michael", "Mitchell", "Nathan", "Nikau",
      "Niko", "Noah", "Oliver", "Oscar", "Pita", "Rangi", "Rawiri", "Reece", "Rhys", "Riley",
      "Ryan", "Sam", "Samuel", "Scott", "Sean", "Shane", "Tama", "Tamati", "Tane", "Teina",
      "Thomas", "Tim", "Toby", "Tom", "Will", "Wiremu", "Zac", "Zach",
    ],
    last: [
      "Adams", "Afoa", "Ah Mau", "Anderson", "Ashby", "Asofa-Solomona", "Bailey", "Barrett", "Beaumont", "Bell",
      "Bennett", "Brown", "Brownlee", "Burgess", "Campbell", "Carey", "Carter", "Clark", "Clarke", "Collins",
      "Cook", "Cooper", "Cribb", "Cronin", "Cross", "Davies", "Davis", "Deans", "Dixon", "Douglas",
      "Edwards", "Elliott", "Ellis", "Evans", "Fainga'a", "Faumuina", "Fekitoa", "Ferguson", "Fifita", "Fisher",
      "Fletcher", "Foster", "Fotu", "Fox", "Fraser", "Galuvao", "Gibson", "Graham", "Grant", "Gray",
      "Green", "Haberecht", "Hall", "Hamilton", "Harris", "Harrison", "Harvey", "Hauraki", "Henderson", "Henry",
      "Hill", "Hohaia", "Holmes", "Hughes", "Hunt", "Hunter", "Ikahihifo", "Ioane", "Jackson", "James",
      "Johnson", "Johnston", "Jones", "Kahu", "Kearney", "Kearns", "Kelly", "Kenny", "King", "Kiriona",
      "Knight", "Latu", "Lawton", "Lee", "Leuluai", "Lewis", "Liu", "Lloyd", "Lomu", "Luke",
      "Manu", "Marshall", "Martin", "Mason", "Matthews", "McCarthy", "McDonald", "McKenzie", "McLean", "Mealamu",
      "Miller", "Mills", "Mitchell", "Moore", "Morgan", "Morris", "Murphy", "Murray", "Napa", "Nelson",
      "Nicholls", "Nikora", "Nonu", "O'Brien", "O'Connor", "Oliver", "Paasi", "Paenga-Amosa", "Parker", "Patterson",
      "Pearce", "Perenara", "Pritchard", "Proctor", "Quinn", "Rangi", "Rapana", "Reid", "Richards", "Riki",
      "Roberts", "Robinson", "Rogers", "Ross", "Russell", "Ryan", "Sao", "Savea", "Scott", "Shaw",
      "Sio", "Smith", "Solomona", "Stevens", "Stewart", "Taia", "Taumalolo", "Taupau", "Taylor", "Thompson",
      "Toia", "Tuivasa-Sheck", "Tuivaiti", "Turner", "Vagana", "Wairau", "Walker", "Wallace", "Walsh", "Ward",
      "Watene", "Watson", "Whare", "White", "Williams", "Wilson", "Wood", "Wright", "Young",
    ],
  },
  SAM: {
    first: [
      "Afa", "Afoa", "Alofa", "Anitelu", "Apa", "Arona", "Ben", "David", "Etuale", "Faalele",
      "Faalogo", "Fale", "Fata", "Fetu", "Frank", "Herman", "Iaone", "Iosefa", "Isaako", "Iulai",
      "Jarome", "Joe", "John", "Jonah", "Junior", "Keneti", "Kenny", "Lagi", "Lama", "Lio",
      "Lisi", "Loki", "Losi", "Lui", "Malakai", "Malu", "Manu", "Mase", "Michael", "Mikaele",
      "Mose", "Niko", "Opa", "Paul", "Peniamina", "Pesamino", "Peter", "Pule", "Ropati", "Sam",
      "Sami", "Sanele", "Siaosi", "Simi", "Sione", "Solomon", "Steve", "Tala", "Tasi", "Taufa",
      "Tavita", "Tim", "Tofa", "Tom", "Tony", "Tui", "Tusi", "Ualesi", "Uili", "Vili",
      "Viliami", "Willie",
    ],
    last: [
      "Ah Mau", "Afoa", "Aiono", "Amituanai", "Anae", "Asofa-Solomona", "Brown", "Faalogo", "Faamausili", "Faasalele",
      "Faatau", "Faitala", "Fale", "Faleono", "Fata", "Fatialofa", "Feleti", "Fesolai", "Fifita", "Filipo",
      "Fuimaono", "Galuvao", "Iosefa", "Iosua", "Kafatolu", "Kitiona", "Lafai", "Laulu", "Leaupepe", "Leilua",
      "Leota", "Leuluai", "Lio", "Liu", "Loto", "Luafalealo", "Luai", "Lufilufi", "Malietoa", "Malolo",
      "Manu", "Masoe", "Matagi", "Mau", "Mauala", "Mulipola", "Napa", "Paasi", "Papalii", "Paulo",
      "Petaia", "Pulu", "Sa", "Sai", "Salavea", "Sao", "Sape", "Savelio", "Sio", "Sioeli",
      "Sitagata", "Soliola", "Solomona", "Su", "Sua", "Suafoa", "Sue", "Sulu", "Suvalele", "Tagaloa",
      "Talagi", "Tasi", "Taula", "Taumalolo", "Taupau", "Tavita", "Teo", "Toala", "Tofilau", "Tuigamala",
      "Tuilaepa", "Tuivasa", "Tuitahi", "Tulafono", "Ualesi", "Umaga", "Vaega", "Vagana", "Vaivai", "Vave",
    ],
  },
  FJI: {
    first: [
      "Akuila", "Apisai", "Apisalome", "Ben", "Epeli", "Eparama", "Eroni", "Frank", "Ilaitia", "Iliesa",
      "Iosefo", "Isikeli", "Isoa", "Jioje", "Jone", "Joseva", "Josua", "Kali", "Kalione", "Kini",
      "Leka", "Leone", "Lote", "Luke", "Maika", "Manasa", "Marika", "Mosese", "Nemani", "Niko",
      "Peni", "Petero", "Pio", "Ratu", "Samisoni", "Samu", "Semi", "Setareki", "Simione", "Sitiveni",
      "Suliasi", "Taito", "Tevita", "Timoci", "Tui", "Uraia", "Viliame", "Waisea", "Waisale", "Wame",
    ],
    last: [
      "Bale", "Baleiwai", "Bukayaro", "Cavuilati", "Dakuitoga", "Delai", "Dradra", "Driu", "Dutt", "Goneva",
      "Hay", "Kamikamica", "Katoa", "Kava", "Koroibete", "Koroisau", "Koroitamana", "Kuruvoli", "Lomani", "Lote",
      "Madigan", "Matawalu", "Monise", "Nabuli", "Nadruku", "Naiyaga", "Nakubuwai", "Nalaga", "Namua", "Nasilasila",
      "Natoga", "Nawai", "Nayacalevu", "Qalova", "Qio", "Rabaka", "Radradra", "Raiwalui", "Ratuvou", "Ravouvou",
      "Sa", "Sadrugu", "Saumaisue", "Saumaki", "Seniloli", "Sivo", "Sokia", "Sovasova", "Tagicakibau", "Tamanisau",
      "Tikoirotuma", "Tikoisuva", "Toka", "Tuisue", "Tuivuna", "Tukidia", "Turaga", "Uluilakeba", "Valetini", "Vakaloloma",
      "Vakatawa", "Vanisi", "Vatuvei", "Vere", "Vodo", "Voka", "Volavola", "Waqa", "Waqaniburotu", "Yalayala",
    ],
  },
  TON: {
    first: [
      "Aisea", "Alipate", "Amanaki", "Atieli", "David", "Etuini", "Feleti", "Fetuli", "Filipe", "Folau",
      "Fotu", "Havea", "Isileli", "Joe", "John", "Junior", "Kotoni", "Latu", "Lisiate", "Mafileo",
      "Manu", "Michael", "Mosese", "Paula", "Penieli", "Salesi", "Sam", "Sami", "Semisi", "Sione",
      "Siosaia", "Sitaleki", "Solomone", "Taufa", "Tevita", "Tongia", "Tui", "Uili", "Viliami", "Willie",
    ],
    last: [
      "Aholelei", "Aho", "Fainga'a", "Faingaanuku", "Faleafa", "Fangupo", "Fekitoa", "Fifita", "Filise", "Finau",
      "Fisilau", "Foketi", "Folau", "Fonua", "Fotu", "Fusitua", "Havea", "Helu", "Hola", "Hopoi",
      "Huni", "Iongi", "Katoa", "Kaufusi", "Koloamatangi", "Langilangi", "Latu", "Lavaka", "Lolohea", "Lousi",
      "Mafileo", "Maile", "Manu", "Moala", "Napa", "Paasi", "Paea", "Pangai", "Penitani", "Pulu",
      "Siale", "Taumalolo", "Taumoepeau", "Taupau", "Taufa", "Taukeiaho", "Tevita", "Toetuu", "Toki", "Tongia",
      "Tuipulotu", "Tuitavake", "Tupou", "Uele", "Uhi", "Vaea", "Vaka", "Vaki", "Vea", "Vunipola",
    ],
  },
  PNG: {
    first: [
      "Alois", "Ase", "Ben", "Bobby", "Clinton", "David", "Dion", "Edwin", "Francis", "Garry",
      "Henry", "Isaac", "Israel", "James", "Joe", "John", "Justin", "Kyle", "Luke", "Mark",
      "Michael", "Moses", "Paul", "Peter", "Ravu", "Sam", "Stanton", "Tommy", "Watson", "Willie",
    ],
    last: [
      "Abavu", "Aila", "Albert", "Bai", "Boas", "Boasman", "Dau", "Ele", "Gairo", "Geia",
      "Genia", "Gima", "Horne", "Ipape", "Kais", "Kanari", "Kapinias", "Kau", "Kaugama", "Kevau",
      "Kila", "Kolo", "Korave", "Kumul", "Kusu", "Lako", "Loko", "Maclean", "Mea", "Meli",
      "Moga", "Moni", "Noki", "Ofo", "Page", "Paniu", "Paraia", "Putt", "Ravu", "Saukuru",
      "Sioni", "Taravatu", "Tonumaipea", "Wabo", "Wai", "Waine", "Wama", "Wem", "Yei", "Yombon",
      "Zimmerman",
    ],
  },
};

export function normalizePlayerFullName(name: string): string {
  return name
    .toLowerCase()
    .trim()
    .replace(/[^\p{L}\p{N}\s'-]/gu, "")
    .replace(/\s+/g, " ");
}

export function getChampNamePoolSizes(): Record<
  ChampNationalityCode,
  { first: number; last: number }
> {
  return (Object.keys(CHAMP_NAME_POOLS) as ChampNationalityCode[]).reduce(
    (acc, code) => {
      const pool = CHAMP_NAME_POOLS[code];
      acc[code] = { first: pool.first.length, last: pool.last.length };
      return acc;
    },
    {} as Record<ChampNationalityCode, { first: number; last: number }>
  );
}
